welcome to user_input
Evercrow/TicTacTry pull request #4
Opened 2022-06-07 07:13 UTC by ILYA-NASA

на этом мои полномочия всё

2022-06-07 21:30 UTC, Evercrow requested changes
Ок,общение с пользователем неплохо оформлено.  Думаю, часть работы с передачей переменных на себя возьмет сборная функция. Мы тут с Геной немного обсудили(можешь пул  запрос посмотреть от него) как примерно должен алгоритм выглядить. Я попробую в readme расписать.

Насчет player_mark - согласен, символом удобнее. Таня, например, с символами и работала) .Но обработку bool удалять не будем , в питоне аргументы гибкие, так что эта часть может пригодиться.

По поводу вход-выхода списка - тут можно подумать, как вообще убрать их, мы уже решили с консолью работать, так что  игрок через консоль визуально поле будет проверять все равно. Но пока оставляяем, только не меняй сам список состояния поля, это будет делать модуль записи(к которому еще и бот будет обращаться).
field_list.append(player_choice) - будет увеличивать нам поле на каждом шагу. 
return field_list, player_choice, player_mark  уже нам вернет кортеж из полученных переменных, информация не пропадет.

Баг логики : 25-29 строки . Текущий код добавит к списку 9 раз цифру игрока, например, X != 1 (плюс, сравнение может и не пройдет, так как сравниваешь строку с цифрой). Здесь нужно либо расшифровывать цифру в позицию на поле через функцию записи, и проверять, пустое ли это поле  (==" ") , либо как-то скопировать и обработать список чисто под себя, чтобы потом уже проверить пустое место. Например, если в field_list[0,0] что-то есть, то добавить во множество занятых полей цифру 1 и так далее. А потом уже можно просто проверять, если ли цифра пользователя в этом множестве

2022-06-08 05:28 UTC, ILYA-NASA commented
Спасибо, Антон! Позже поработаю над кодом.
По поводу вход-выхода списка - посмотри пример (раскомментированный код из моего репо https://github.com/ILYA-NASA/HelloPython/blob/main/leson8.py ). Тут функция attack не делает ретерн, а сразу меняет значения последовательности вне функции, думаю нам можно применить такой же принцип?

2022-06-09 15:34 UTC, Evercrow commented
Насчет изменения внешней переменной не знал, нужно будет потестить, но в питоне - вполне возможно.
Тем проще, на вход и выход можно со списком не заморачиваться, ты его и сам вызвать  сможешь.
Я вижу, что ты новый readme читал, но там же еще пример  переменной списка поля list_game = [['x','o','o'],['o','x','x'],['x','o',' ']]  , и его вызова list_game[2][2] , как 9-го поля. 
 
Вобщем, твою функцию состыковать с уже написанными будет нельзя(иначе все остальные модули нужно будет переписать), зато дописать до самостоятельной игры уже можно :)

Думаю, функцию расшифровки все же напишем отдельно , так что в своей программе валидность хода можешь не проверять(заполненность ячейки). И со счетчиком не заморачивайся, это во внешней, 7-й функции будет. 
Так что, по сути, в твоей проге останутся только консольные запросы, их проверка на ошибку(что ты уже делаешь), и вызов функции записи хода, например, по синтаксису WriteMove(9,метка_игрока) . WriteMove тебе будет возвращать флаг true, если  ход записан, или false - если ячейка уже заполнена,тогда уже переспрашиваешь пользователя.

Вход твоей функции, с учетом твоего замечания про внешние переменные, тогда будет только меткой игрока, а выход у нее пустой(void- функция) .

2022-06-09 19:24 UTC, Evercrow requested changes
в "разговоре" дал фидбек, жду финальной версии)

2022-06-12 07:37 UTC, Evercrow approved these changes
Ок. То, что ты в комментах пишешь - это прописываем в main

2022-06-12 07:37 UTC, merged